# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e9a1af4ccd33da9f2ac4e9a8825e1b94e08bfd3b6387a2c41e2d35011ca1647379e453ba2a2125052068862df65402e8a612627c0b603a43813430cd765e184

test:
  secret_key_base: 4a1717c429f72b70fa125a0fa90968f55111a9e4a2d0d9e61f782fdd08b46c00f6a4cc2bf411af777cddc797286c9750bd35a9880fb4309cd123090bfe6aaa0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
